### ISSUE TITLE
Episode one - CH notes

### ISSUE THREAD

**Issue by chennesy** [umn-dash/r-shiny#1]
[Ideas for episode 1:](https://umn-dash.github.io/r-shiny/shiny_1.html)

- [x] - After[ key concept 1](https://umn-dash.github.io/r-shiny/shiny_1.html#key-concept-1-all-websites-are-boxes-within-boxes) add an exercise to rewrite a simple HTML div in R Shiny.
- [x] - Add HTML code that shows how [the image](https://umn-dash.github.io/r-shiny/fig/clipboard-3243983914.pn) illustrating block and inline elements would be constructed using HTML.
- [x] - In [CSS 101](https://umn-dash.github.io/r-shiny/shiny_1.html#css-101), it might help learners if you add code chunks showing both HTML and R Shiny examples that a targetered by the CSS `p.intro` and `div#firstintro` selectors.

**Comment by BajczA475** [comment]
@chennesy Can you clarify the third bullet here a little further? The CSS code here would be identical, so is the goal to show them what the HTML looks like vs. what the Shiny looks like? If so, that feels like it would belong better in the HTML section...Maybe I'm just not following your logic :)

**Comment by BajczA475** [comment]
First two items here are done and will be present in the next commit!

**Comment by chennesy** [comment]
@BajczA475 Yeah, was just thinking that the descriptions of how the CSS selectors work could be reinforced by showing code that would match specific rules. Right now it's all a bit abstract.

For example, under:
1. The first target is paragraph boxes (p()s), but only those with the intro class attribute...

It might be helpful to show something like:
```
<p class = "intro">This paragraph is targeted by the _p.intro_ CSS rule.</p>
<p class = "body">This paragraph would not be affected by the CSS rule.</p>
```

But if it adds too much clutter, feel free to skip it!

**Comment by BajczA475** [comment]
@chennesy Cool--added something just now which should be live soon--please let me know what you think!
