### ISSUE TITLE
Edit index.md

### ISSUE THREAD

**Issue by chennesy** [umn-dash/r-shiny#2]
Edit [the index.md](https://github.com/umn-dash/r-shiny/blob/main/index.md) file to add a brief description of the lesson that will appear at the beginning of the [lesson homepage](https://umn-dash.github.io/r-shiny/), before the setup instructions in learners/setup.md.

**Comment by BajczA475** [comment]
Done! Will be pushed through in the next commit. I just copy-pasted what I'd already written via email previously.
