### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by chennesy** [umn-dash/r-shiny#4]
For the install instructions in the[ setup](https://umn-dash.github.io/r-shiny/index.html#required-setup) and [episode 2](https://umn-dash.github.io/r-shiny/shiny_2.html#detour-installing-packages) when running:
`install.packages("shiny", "dplyr", "ggplot2", "leaflet", "DT", "plotly", "gapminder", "sf")`

 I got an error that suggests install.packages is expecting a different argument in the second position:
`Warning in install.packages :
  'lib = "dplyr"' is not writable`

I was able to fix it running this instead:
`install.packages(c("shiny", "dplyr", "ggplot2", "leaflet", "DT", "plotly", "gapminder", "sf"))`

**Comment by BajczA475** [comment]
Good catch! This will be fixed in the next push.
