### ISSUE TITLE
episode 4: table disappears

### ISSUE THREAD

**Issue by chennesy** [umn-dash/r-shiny#7]
Not sure why, but when I run the server.R code from [this part of the lesson](https://umn-dash.github.io/r-shiny/shiny_4.html#more-or-less-basic-dt) my tabular data all disappears from my app. When I change the server code in the next section (to round the gdpPercap column, make the continent column center-aligned, and highlight all rows with lifeExp values > 70 in pink) it works again.

**Comment by BajczA475** [comment]
@chennesy Good catch--I use an outdated outputId here (basic_table) instead of table1. That's why generic names are bad! Next push should contain that fix.

**Comment by BajczA475** [comment]
@chennesy Good catch--I use an outdated outputId here (basic_table) instead of table1. That's why generic names are bad! Next push should contain that fix.

**Comment by N01666282** [comment]
{
  "ai": {
    "binding": "AI"
  }
}
